//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace MessagesSender.DAL.Model
{
    public class AtlasSW
    {
        [Key]
        [Column("rowid")]
        public int RowId { get; set; }
        public int Id { get; set; }
        [Column("atlas_version")]
        public string AtlasVersion { get; set; }
        [Column("complex_type")]
        public string ComplexType { get; set; }
        public string Language { get; set; }
        public string Multimonitor { get; set; }
        [Column("xilibs_version")]
        public string XilibsVersion { get; set; }

        public DateTime? Updated { get; set; }
        public bool Active { get; set; }
    }
}
