//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagesSender.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentDicomParam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentDicomParam()
        {
        }
    
        public int Id { get; set; }
        public string DicomAttribute { get; set; }
        public string Value { get; set; }
        public string ParameterComment { get; set; }
    }
}
