//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace MessagesSender.DAL.Model
{
    public class News
    {
        public int Id { get; set; }
        public string Tbl { get; set; }
        public int RowId { get; set; }
        public string Type { get; set; }

        public DateTime? Updated { get; set; }
        public bool Active { get; set; }
    }
}
