//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagesSender.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Study45
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Study45()
        {
            AccessionNumber = Diagnosis = DicomUid = DicomId = Name = OperatorsName = ProcedureDescription = string.Empty;
            
        }
    
        public int Id { get; set; }
        public int PatientId { get; set; }
        public string DicomUid { get; set; }
        public string DicomId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> FactStartDate { get; set; }
        public Nullable<System.TimeSpan> FactStartTime { get; set; }
        public int StudyStatus { get; set; }
        public string ProcedureDescription { get; set; }
        public string AccessionNumber { get; set; }
        public int ImageCount { get; set; }
        public double TotalDose { get; set; }
        public double TotalDoseGr { get; set; }
        public Nullable<int> RefInstitutionId { get; set; }
        public Nullable<int> RefPhysicianId { get; set; }
        public string Diagnosis { get; set; }
        public System.DateTime PlanStartDate { get; set; }
        public System.TimeSpan PlanStartTime { get; set; }
        public Nullable<int> DiagnosisTypeId { get; set; }
        public Nullable<int> AuxEditId { get; set; }
        public Nullable<System.DateTime> LastStudyUpdateDate { get; set; }
        public Nullable<int> ContrastId { get; set; }
        public int PregnancyStatus { get; set; }
        public string OperatorsName { get; set; }
        public Nullable<int> PhysicianId { get; set; }
        public Nullable<int> HosDepartmentId { get; set; }
        public int Constitution { get; set; }
        public Nullable<double> KermaPower { get; set; }
        public Nullable<double> KermaSum { get; set; }
        public int AuxStudyStatus { get; set; }
        public string SmpName { get; set; }
        public string MkbCode { get; set; }

        public Nullable<int> CancelationReasonId { get; set; }
    }
}
